### PR TITLE
Remove setters of Body.IsStatic and Body.IsKinematic

### PR DESCRIPTION
**Pull request by nkast**
When you set any of those to false, the body defaults to Dynamic which has unexpected results. 

ex.
body.IsStatic = true; // BodyType == Static
body.IsKinematic = false; // BodyType == Dynamic

### CODE REVIEW

**Comment by nkast** [comment]
Thanks @damian-666.
The users are now forced to explicitly set the bodyType and not through guesswork.

What do you think about deprecating/removing the getters?
I had to either remove IsStatic and IsKinematic or add the missing IsDynamic.

I can see that body.IsStatic can lead to sorter and easy to read code. On the other hand it adds more surface to the API.

**Comment by damian-666** [comment]
i think you might as well leave it in because it is a breaking api change and it does have meaning and is readable.    my code uses  if (IsStatic) in many places..  And we used IsStatic = true as a way to work around issues with sleep and joints and vibrating things    So ideally if isstatic = true didnt have any implementation issues like change the value  of dynamic vs kinematic then it would be useful to have, but i wont miss it .  Since I just spent 4 weeks porting about 4 man-years  of code from Silverlight to UWP/ RT, I am a little jaded with api breakage that is related to cleanup.

**Comment by damian-666** [comment]
Its almost as if Static should be a separate bool rather than being part of a tri state..  MSFT has an analogy when visibility was a tristate  hidden, collapse and visible,  and now its a still an  enum but with  two. states.hidden and collapsed.    https://msdn.microsoft.com/en-us/library/system.windows.visibility(v=vs.110).aspx   they prolly set up meetings and argued about it philosophically for weeks .

**Comment by damian-666** [comment]
in general, one struggle in open source is all the branching that happens requiring tons of merges. So i would prefer to avoid especially pervasive changes unless they are compelling because diffing and extracting features is hard.  Say there s is a  10+x   speedup ( like bullet has demo'd ) for piling IsBullet items,  and maybe then running parallel with  Alea GPGPU ..  then for  taking just those new promising  changes.  All the little optimizations or cleanup that went into  later Farseer and or velcro , combined with my teams now lamented decision to build serialization directly  into the lib and a copy..  is why we never bothered to move to the latest version.   its hard to know if there is a canonical branch, which one that is, and how lively it is...but im happy this branch is alive and kicking...i wish i had time to contribute to  helping to build it in near term

**Pull request merged**
